<?php
/*
 *
 *
 */
exit("main.phtl");
?>CZzzXcZX
<div class='container'>
    <div class='hcontainer'>
        <?php echo $this->render('includes/headercontainer.phtml'); ?>
    </div>
    <div class='mcontainer'>
        <div class='rcontainer'>
            <?php echo $this->render('includes/dedicateblock.phtml'); ?>
        </div>
        <div class='lcontainer'>
            <?php echo $this->render('includes/lcontainer.phtml'); ?>
        </div>
    </div>
    <div class='fcontainer'></div>
</div>
<?php echo $this->render('includes/chat.phtml'); ?>
