<div class='respwdbox'>
	<div class='respwdboxl'>
		<a href='/<?php echo $this->id ?>'><img
			alt="<?php echo $this->fname; ?>"
			src="<?php echo $this->profile_image_link; ?>"></a>
	</div>
	<div class='respwdboxr'>
		<div>Hi <?php $this->fname." ".$this->lname." your email is ".$this->email  ?></div>
		<form method='post' action='/resetpassword'>
			<input type='password' value='' name='password' /> <input
				type='password' value='' name='confirm_password' /> <input
				type='hidden' value='<?php echo $this->email;?>' name='email' /><input
				type='hidden' value='<?php echo $this->key;?>' name='key' /> <input
				type='submit' value='submit' />
		</form>
	</div>
</div>