<!Doctype>
<html>
    <body>

        <table cellspacing="0" cellpadding="0" border="0" width="100%;"
               style="border-collapse: collapse">

            <tr
                style='color: #111; font-family: Arial, sans-serif; font-size:0.833em;'>
                <td style='font-size:0.833em;font-weight:bold;padding: 15px;'>Emoera</td>
            </tr>
            <tr style="border-bottom: solid 1px #e5e5e5">
                <td height="1" style="line-height: 1px">&nbsp;</td>
            </tr>
            <tr>
                <td width="5%" style="margin: 0; padding: 15px 0; direction: ltr"></td>
                <td width="70%"
                    style="font-family: Arial, sans-serif; direction: ltr">
                    <table cellspacing="0" cellpadding="0" border="0" width="100%;"
                           style="border-collapse: collapse">
                        <tbody>

                            <tr>
                                <td style="padding: 0px;">

                                    <table>
                                        <tr
                                            style='color: #111; font-family: Arial, sans-serif; font-size:0.833em;'>
                                            <td height="35" style="line-height: 16px">Hi <?php echo ucFirst($this->toname); ?></td>
                                        </tr>
                                        <tr>
                                            <td style="font-size:0.833em;">
                                                <table>
                                                    <tr
                                                        style='color: #111; font-family: Arial, sans-serif; font-size:0.833em;'>
                                                        <!--<td valign="top" style=""><a href='<?php echo BASE_PATH . $this->id ?>'><?php echo $this->fromname; ?>'</a></td>-->
                                                        <td></td><td style="font-weight: normal"><a href='<?php echo BASE_PATH . $this->myid ?>'><?php echo ucFirst($this->myname); ?></a> wants to be your friend in Emoera.</td>
                                                    </tr>
                                                    <tr style="border-top: solid 1px #e5e5e5">
                                                        <td height="16" style="line-height: 16px">&nbsp;</td>
                                                    </tr>
                                                    <tr>
                                                        <td></td>
                                                        <td><a bgcolor="maroon" align="center"
                                                               style="background-color: maroon; border: 1px solid #111; border-radius: 4px; color: #fff; cursor: pointer; font-size: 15px; margin-right: 6px; padding: 2px 9px; text-decoration: none; text-transform: capitalize"
                                                               valign="middle" height="40" target="_blank" href='<?php echo BASE_PATH ?>'>Register</a> in emoera and enjoy his friendship.</td>
                                                    </tr>
                                                </table>
                                            </td>
                                        </tr>
                                        <tr style="border-bottom: solid 1px #e5e5e5">
                                            <td height="16" style="line-height: 16px">&nbsp;</td>
                                        </tr>

                                        <tr style='font-size: 11px;color:#999;'>
                                            <td style="">This message was sent to <a target="_blank"
                                                                                     style="color: #3b5998; text-decoration: none"
                                                                                     href="mailto:bagga.gurjeetsingh@gmail.com">bagga.gurjeetsingh@gmail.com</a>.
                                                If you don't want to receive these emails from gurjeetbagga in the
                                                future, please <a target="_blank"
                                                                  style="color: #3b5998; text-decoration: none" href="#">unsubscribe</a>.<br>Emoera,Inc.,
                                                Attention:Bangalore 560037
                                            </td>
                                        </tr>
                        </tbody>
                    </table>
                </td>
            </tr>

        </table>
    </td>
</tr>
</table>