<!Doctype>
<html>
<body>

	<table cellspacing="0" cellpadding="0" border="0" width="100%;"
	style="border-collapse: collapse">

	<tr
	style='color: #111; font-family: Arial, sans-serif; font-size:0.833em;'>
	<td style='font-size:0.833em; padding: 10px;'>Emoera</td>
</tr>
<tr style="border-bottom: solid 1px #e5e5e5">
	<td height="1" style="line-height: 1px">&nbsp;</td>
</tr>
<tr>
	<td width="5%" style="margin: 0; padding: 15px 0; direction: ltr"></td>
	<td width="70%"
	style="font-family: Arial, sans-serif; direction: ltr">
	<table cellspacing="0" cellpadding="0" border="0" width="100%;"
	style="border-collapse: collapse">
	<tbody>

		<tr>
			<td style="padding: 0px;">

				<table>
					<tr
					style='color: #111; font-family: Arial, sans-serif; font-size:0.833em;'>
					<td height="35" style="line-height: 16px">Hi <?php echo ucFirst($this->fname); ?></td>
				</tr>

				<tr>
					<td style="font-size:0.833em;">
						<table>
						<tr><td style="font-weight: normal;font-size:0.833em;">Some one requesting to reset your password.</td></tr>
						<tr></tr>
							<tr
							style='color: #111; font-family: Arial, sans-serif; font-size:0.833em;'>
							
							<td style="font-weight: normal">please <b><a href="<?php echo BASE_PATH?>resauth?email=<?php echo $this->toemail ?>&&?secretkey=<?php echo $this->key ?>">Reset</a></b> your password, If you are having trouble accessing your account.
							</td>
						</tr>
						<tr style="border-top: solid 1px #e5e5e5">
							<td height="16" style="line-height: 16px">&nbsp;</td>
						</tr>
						<tr >
							<td style="font-weight: normal;font-size:0.833em;">
								<table>
									<tr>
										<td style="font-weight: normal;font-size:0.833em;">Thanks</td>
									</tr>
									<tr>
										<td style="font-weight: normal;font-size:0.833em;">gurjeetbagga</td>
									</tr>
								</table>
							</td>
						</tr>
						</table>
					</td>
				</tr>
				<tr style="border-bottom: solid 1px #e5e5e5">
					<td height="16" style="line-height: 16px">&nbsp;</td>
				</tr>

				<tr style='font-size: 11px;color:#999;'>
					<!--td style="">This message was sent to <a target="_blank"
						style="color: #3b5998; text-decoration: none"
						href="mailto:bagga.gurjeetsingh@gmail.com"><?php echo $this->toemail ?></a>.
						If you don't want to receive these emails from gurjeetbagga in the
						future, please <a target="_blank"
						style="color: #3b5998; text-decoration: none" href=<?php BASE_PATH ?>"unsubscribe">unsubscribe</a>.<br>Emoera,Inc.,
						Attention:Bangalore 560037
					</td-->
				</tr>
			</tbody>
		</table>
	</td>
</tr>

</table>
</td>
</tr>
</table>
