<!Doctype>
<html>
<body>
	<table cellspacing="0" cellpadding="0" border="0" width="100%;"
		style="border-collapse: collapse">

		<tr>
			<td width="10%" style="margin: 0; padding: 15px 0; direction: ltr"></td>
			<td width="70%"
				style="font-family: Arial, sans-serif; direction: ltr">
				<table cellspacing="0" cellpadding="0" border="0" width="100%;"
					style="border-collapse: collapse">
					<tbody>
						<tr
							style='color: #111; font-family: Arial, sans-serif; font-size: 14px;'>
							<td style='font-size: 15x; padding: 10px;'>Emoera</td>
						</tr>
						<tr style="border-bottom: solid 1px #e5e5e5">
							<td height="16" style="line-height: 16px">&nbsp;</td>
						</tr>
						<tr>
							<td style="padding: 20px;">

								<table>
									<tr
										style='color: #111; font-family: Arial, sans-serif; font-size: 14px;'>
										<td height="35" style="line-height: 16px">Hi Sachin</td>
									</tr>
									<tr>
										<td style="font-size: 14px;">
											<table>
												<tr
													style='color: #111; font-family: Arial, sans-serif; font-size: 14px;'>
													<td valign="top" style=""><a href='#'><img width="35px"
															src='https://lh3.googleusercontent.com/-64CWplLUOFA/AAAAAAAAAAI/AAAAAAAAAeQ/3HiwG4X3yJE/photo.jpg' />
													</a></td>
													<td style="font-weight: normal">Gurjeet singh wants to be
														your friend in Emoera.</td>
												</tr>
												<tr style="border-top: solid 1px #e5e5e5">
													<td height="16" style="line-height: 16px">&nbsp;</td>
												</tr>
												<tr>
													<td></td>
													<td><a bgcolor="maroon" align="center"
														style="background-color: maroon; padding: 10px; color: #fff"
														valign="middle" height="50" target="_blank" href='#'>Accept</a>
														his Friend Request.</td>
												</tr>
											</table>
										</td>
									</tr>
									<tr style="border-top: solid 1px #e5e5e5">
										<td height="16" style="line-height: 16px">&nbsp;</td>
									</tr>

									<tr style="">
										<td height="25" style="line-height: 16px">&nbsp;</td>
									</tr>
									<tr
										style='color: #111; font-family: Arial, sans-serif; font-size: 14px;'>
										<td style="">Thanks</td>
									</tr>
									<tr
										style='color: #111; font-family: Arial, sans-serif; font-size: 14px;'>
										<td style="">Emoera</td>
									</tr>
									<tr style="border-bottom: solid 1px #e5e5e5">
										<td height="16" style="line-height: 16px">&nbsp;</td>
									</tr>
									<tr>
										<td height="46" style="line-height: 16px">&nbsp;</td>
									</tr>
									<tr>
										<td style="">This message was sent to <a target="_blank"
											style="color: #3b5998; text-decoration: none"
											href="mailto:bagga.gurjeetsingh@gmail.com">bagga.gurjeetsingh@gmail.com</a>.
											If you don't want to receive these emails from Facebook in
											the future, please <a target="_blank"
											style="color: #3b5998; text-decoration: none" href="#">unsubscribe</a>.<br>Emoera,Inc.,
											Attention:Bangalore 560037
										</td>
									</tr>
									</tbody>
								</table>
							</td>
						</tr>
				
				</table>
			</td>
		</tr>
	</table>