<style type="text/css">
    .tc{
        text-align: center;
    }
    .slideshowcontainer{
        margin-top: 40px;
        width: 962px;
        padding: 20px;
        border-color: #E5E5E5 #DBDBDB #D2D2D2;
        box-shadow: 0 1px 3px rgba(0, 0, 0, 0.3);
        z-index: 9999;
        top: 150px;
        left: 250px;
        background-color: #fff;
        display: inline-block;
    }  
    .slideshowcontainerim{
        min-height: 150px;
        display: inline-block;
        float: left;
    }
    .slideshowcontainerli{
        position: relative;
        clear: both;
        display: inline-block;
        margin: 5px;
        padding: 2px;
        border: 1px solid #fff;
    }
    .slideshowcontainerli:hover{
        border: 1px solid #eee;
        background-color: #f8f8f8;
    }
    .slideshowcontainerlidivbx{
        /*float: left;*/
        padding: 2px;
        margin-right: 10px;
        overflow: hidden;
        text-align: center;
        box-shadow: 2px 2px 2px #eee;
        border: 1px solid #ccc;
        width: 60px;
        float: left;
    }
    .slideshowcontainervi{
        float: right;
    }
    .slideshowcontainervilbxlcntnr{
/*        background-color: #f8f8f8;
        border-radius: 5px;*/
    }
        .slideshowcontainervilbxlcntnrimgpreview{
/*border:1px solid #d7dada;*/
-webkit-border-radius: 3px; 
-moz-border-radius: 3px;
border-radius: 3px;
font-size:12px;
font-family:arial, helvetica, sans-serif; 
margin: 10px 10px 10px 10px; 
text-decoration:none; 
display:inline-block;
text-shadow: -1px -1px 0 rgba(0,0,0,0.3);
font-weight:bold; 
color: #FFFFFF;
 background-color: #f4f5f5; 
 background-image: -webkit-gradient(linear, left top, left bottom, from(#f4f5f5), to(#dfdddd));
 background-image: -webkit-linear-gradient(top, #f4f5f5, #dfdddd);
 background-image: -moz-linear-gradient(top, #f4f5f5, #dfdddd);
 background-image: -ms-linear-gradient(top, #f4f5f5, #dfdddd);
 background-image: -o-linear-gradient(top, #f4f5f5, #dfdddd);
 background-image: linear-gradient(to bottom, #f4f5f5, #dfdddd);
 filter:progid:DXImageTransform.Microsoft.gradient(GradientType=0,startColorstr=#f4f5f5, endColorstr=#dfdddd);

    }
    .slideshowcontainervilbx{

        margin-right: 10px;
    }
    .slideshowcontainervirbx{
        /*float: right;*/
    }
    .slidshowcircleconverter{
    }
    .slideshowcontainervilbxlcntnrimgpreviewslctr{
        display: none;
    }
    .slideshowcontainervilbxlcntnrimgpreviewbx{
        position: relative;
        height: 240px;
        width:426px;
        overflow: hidden;
        box-shadow: 2px 2px 2px #eee;
        border: 1px solid #ccc;
    }
    .slideshowcontainervirbxvidpreview{
        position: relative;
        height: 240px;
        width:426px;
        overflow: hidden;
        box-shadow: 2px 2px 2px #eee;
        border: 1px solid #ccc;
    }
    .slideshowcontainervilbxlcntnrimgpreviewbxli{
        /*background-color: #111;*/
        text-align: center;
        position: relative;
    }
    .slideshowcontainervilbxlcntnrimgpreviewbxlidiv{
        /*background-color: rgba(111, 111, 111, 0.4);*/
        color: #111;
        font-size: 14px;
        bottom: 40px;
        height: 42px;
        position: absolute;
        right: 70px;
        width: 200px;
        text-align: left;
    }
    .slideshowleftarrow{
        left: 0;
        background-repeat: no-repeat;
    }
    .slideshowrightarrow{
        right: 0;
        background-repeat: no-repeat;
    }
    .slideshowleftarrow:hover{

        background-image: url('../public/images/left_white.png');

    }
    .slideshowrightarrow:hover{
        background-image: url('../public/images/right_white.png');
    }
    .slideshowleftarrow:hover,.slideshowrightarrow:hover{
        /*background-color: rgba(111,111,111,0.9);*/
        margin-top: 20%;
    }
    .slideshowleftarrow,.slideshowrightarrow{
        position: absolute;
        width: 60px;
        height: 100%; 
        /*background-color: rgba(111,111,111,0.9);*/

    }
    .slideshowcontainervilbxrcntnr{
        margin-top: 5px;
        margin-bottom: 5px;
        margin-left: 170px;        
    }
    .slideshowcontainerlidiv{
        border: 1px solid #eee;
        font-size: 11px;
        padding: 2px;
        height: 50px;
        overflow-y: auto;
        width: 220px;
        text-align: left;
        float: right;
    }

    .slideshowcontainerli img ,.txteditorbxbimgslctrli img{
        /*float: left;*/
    }

    .slideshowcontainerimbx{
        width: 320px;
    }

    .convert_button{
        width: 80px;
        height: 80px;        
        line-height: 80px;
        border-radius: 80px;
        background-color: #f8f8f8;
        cursor:pointer;
        border:1px solid #d7dada; 
        -webkit-border-radius: 3px; 
        -moz-border-radius: 3px;
        border-radius: 80px;font-size:12px;
        font-family:arial, helvetica, sans-serif; 
        padding: 10px 10px 10px 10px; 
        text-decoration:none; 
        display:inline-block;
        text-shadow: -1px -1px 0 rgba(225,225,225,0.3);
        font-weight:bold; 
        color: #666;
        background-color: #f4f5f5; 
        background-image: -webkit-gradient(linear, left top, left bottom, from(#f4f5f5), to(#dfdddd));
        background-image: -webkit-linear-gradient(top, #f4f5f5, #dfdddd);
        background-image: -moz-linear-gradient(top, #f4f5f5, #dfdddd);
        background-image: -ms-linear-gradient(top, #f4f5f5, #dfdddd);
        background-image: -o-linear-gradient(top, #f4f5f5, #dfdddd);
        background-image: linear-gradient(to bottom, #f4f5f5, #dfdddd);filter:progid:DXImageTransform.Microsoft.gradient(GradientType=0,startColorstr=#f4f5f5, endColorstr=#dfdddd);
    }

    .convert_button:hover{
        border:1px solid #bfc4c4;
        background-color: #d9dddd; background-image: -webkit-gradient(linear, left top, left bottom, from(#d9dddd), to(#c6c3c3));
        background-image: -webkit-linear-gradient(top, #d9dddd, #c6c3c3);
        background-image: -moz-linear-gradient(top, #d9dddd, #c6c3c3);
        background-image: -ms-linear-gradient(top, #d9dddd, #c6c3c3);
        background-image: -o-linear-gradient(top, #d9dddd, #c6c3c3);
        background-image: linear-gradient(to bottom, #d9dddd, #c6c3c3);filter:progid:DXImageTransform.Microsoft.gradient(GradientType=0,startColorstr=#d9dddd, endColorstr=#c6c3c3);
    }
</style>
<div class="slideshowcontainer">
    <div class="slideshowcontainerhdr">
        <form action="" id="slideshowfileform" enctype="multipart/form-data">
            <input type="file" id="slideshowfileid" value="upload file" name="slideshowfile[]" multiple="multiple" />
            <input type="button" class="slideshowfilecl" value="create slideshow" />
        </form>
    </div>
    <div class="slideshowcontainerbdy">
        <form action="///var/www/Mandrill" id="slideshowcontainerbdyfrm" method="Post" enctype="">
            <div class="slideshowcontainerim">
                <div class="slideshowcontainerimbx">
                    <ul>
                    </ul>
                </div>
            </div>            
        </form>
        <div class="slideshowcontainervi">
            <div class="slideshowcontainervilbx">
                <div class="slideshowcontainervilbxlcntnr">
                    <div class="slideshowcontainervilbxlcntnrimgpreview">
                        <div class="slideshowcontainervilbxlcntnrimgpreviewbx">
                            <div class="slideshowleftarrow">
                                <div class=""></div>
                            </div>
                            <div class="slideshowrightarrow"></div>
                            <ul>
                                <li class="slideshowcontainervilbxlcntnrimgpreviewbxli">
                                    
                                    <div class="slideshowcontainervilbxlcntnrimgpreviewbxlidiv"></div></li>
                            </ul>
                        </div>
                    </div>
                    <div class='slideshowcontainervilbxlcntnrimgpreviewslctr'>
                        <div class='txteditorbxa'> text view:                       
                            <input type='radio' name='textboxselector' value='left' />left
                            <input type='radio' name='textboxselector' value='top' />top
                            <input type='radio' name='textboxselector'  value='right' />right
                            <input type='radio' name='textboxselector' value='bottom' />bottom
                            <input type='radio' name='textboxselector' value='center'/>center
                        </div>
                        <div class='txteditorbxb'>
                            background : <input type='radio' name='textboxselectorblur'/>blur
                            <input type='radio' name='textboxselectorclear'/>clear
                            <div class='txteditorbxbimgslctr'>
                                <div class='txteditorbxbimgslctra'>
                                    <input type="file"/>
                                </div>
                                <div class='txteditorbxbimgslcrb'>
                                    <ul>
                                        <li class='txteditorbxbimgslctrli'><img src='../public/images/tempimg/thumbnail_1.jpg' class='txteditorbxbimgslctrimg'/><div class='txteditorbxbimgslctrdiv'></div></li>
                                        <li class='txteditorbxbimgslctrli'><img src='../public/images/tempimg/thumbnail_1.jpg' class='txteditorbxbimgslctrimg'/><div class='txteditorbxbimgslctrdiv'></div></li>
                                        <li class='txteditorbxbimgslctrli'><img src='../public/images/tempimg/thumbnail_1.jpg' class='txteditorbxbimgslctrimg'/><div class='txteditorbxbimgslctrdiv'></div></li>
                                        <li class='txteditorbxbimgslctrli'><img src='../public/images/tempimg/thumbnail_1.jpg' class='txteditorbxbimgslctrimg'/><div class='txteditorbxbimgslctrdiv'></div></li>
                                        <li class='txteditorbxbimgslctrli'><img src='../public/images/tempimg/thumbnail_1.jpg' class='txteditorbxbimgslctrimg'/><div class='txteditorbxbimgslctrdiv'></div></li>
                                        <li class='txteditorbxbimgslctrli'><img src='../public/images/tempimg/thumbnail_1.jpg' class='txteditorbxbimgslctrimg'/><div class='txteditorbxbimgslctrdiv'></div></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="slideshowcontainervilbxrcntnr">
                    <input class="slideshowimagelst" type="hidden" value="" name="slideshowimage[]" />
                    <div class="convert_button slidshowcircleconverter tc">make video</div>

                </div>
            </div>
            <div class="slideshowcontainervirbx">
                <div class="slideshowcontainervirbxvidpreview">                   
                    
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    window.onbeforeunload = function(event) {
        var message = 'Sure you want to leave?';
        if (typeof event == 'undefined') {
            event = window.event;
        }
        if (event) {
            event.returnValue = message;
        }
        return message;
    }
    $('.slideshowfilecl').click(function() {
        // var el = $(this);
        var formData = new FormData($('#slideshowfileform')[0]);

        $.ajax({
            type: "POST",
            url: "/user/getuploadedimage/",
            data: formData,
            async: false,
            cache: false,
            dataType: 'Json',
            contentType: false,
            processData: false,
            success: function(slideshowData)
            {
//                console.log(slideshowData);
//                var slideshowData = eval('(' + slideshowData + ')');
                $.each(slideshowData, function(i, value) {
                    $(".slideshowcontainervilbxlcntnrimgpreviewbx ul").append("<li class='slideshowcontainervilbxlcntnrimgpreviewbxli'><img src = '" + value.mediumurl + "'/></li>");
                    $('.slideshowcontainerimbx ul').append(
                            "<li class='slideshowcontainerli'>\n\
                            <div class='slideshowcontainerlidivbx'><img src=" + value.smallurl + "></div>\n\
                    <div  class='slideshowcontainerlidiv' contenteditable='true' >\n\
                    </div>\n\
                    <input class='slideshowcontainerlidivbximgval' type='hidden' name='image[" + i + "][url][]' value='" + value.mediumurl + "' />\n\
                    <input class='slideshowcontainerlidivbximgvall' type='hidden' name='image[" + i + "][lurl][]' value='" + value.url + "' />\n\
                    <input class='slideshowcontainerlidivbxtxtval' type='hidden' name='image[" + i + "][text][]' value='' />\n\
                    <input class='slideshowcontainerlidivbxtxtnam' type='hidden' name='image[" + i + "][name][]' value='" + value.name.basename + "' />\n\
                    </li>"
                            );
                });

            },
            error: function(e) {

            }
        });
        return false;
    });
    $(".slidshowcircleconverter").on('click', function() {
        var form = $('#slideshowcontainerbdyfrm').serialize();
       
        var data = $(".slideshowimagelst").val();
        $.ajax({
            url: '/user/createvideo/',
            type: 'POST',
            data: form,
            success: function(data) {
//                 $(".slideshowcontainervirbxvidpreview").html("<img src='"+data+"'/>");
//                console.log("data = "+data);
                var el = "<OBJECT CLASSID='clsid:02BF25D5-8C17-4B23-BC80-D3488ABDDC6B' WIDTH='160' HEIGHT='144' CODEBASE='http://www.apple.com/qtactivex/qtplugin.cab'><PARAM class='videoplayer' name='SRC' VALUE='"+data+"'><PARAM name='AUTOPLAY' VALUE='true'><PARAM name='CONTROLLER' VALUE='false'><EMBED class='videoplayer' SRC='"+data+"' WIDTH='426' HEIGHT='240' AUTOPLAY='true' CONTROLLER='false' PLUGINSPAGE='http://www.apple.com/quicktime/download/'></EMBED></OBJECT>";
                $(".slideshowcontainervirbxvidpreview").html(el);
            }
        });
    });

    $(".slideshowcontainerimbx ul").on('keyup', '.slideshowcontainerli', function() {
        var text = $(this).find('.slideshowcontainerlidiv').text();
        $(this).find('.slideshowcontainerlidivbxtxtval').val(text);
        $(".slideshowcontainervilbxlcntnrimgpreviewbxlidiv").html($(this).find('.slideshowcontainerlidiv').text());
    });
    $(".slideshowcontainerimbx ul").on('click', '.slideshowcontainerli', function() {
        var src = $(this).find('.slideshowcontainerlidivbximgval').val();
        $('.slideshowcontainervilbxlcntnrimgpreviewbx ul li  img').attr('src', src);
        $('.slideshowcontainervilbxlcntnrimgpreviewbx ul li .slideshowcontainervilbxlcntnrimgpreviewbxlidiv').html($(this).find('.slideshowcontainerlidiv').text());
    });
</script>