<style>
#emailreqbx{
	width:335px;
	margin: 20px auto;
	  border:1px solid rgba(105, 81, 81, 0.09);
  padding:20px 60px 60px;

}
#emailreqfrm{
	width:335px;
	margin: 20px auto;

}
.emailreqinp{	
	width: 335px;
  height: 32px;
  line-height: 29px;
  font-size: 12px;
  direction: ltr;
  display: block;
  margin: 5px 0;
  padding: 0 8px;
  background: white;
  border: 1px solid #D9D9D9;
  border-top: 1px solid silver;
  -webkit-box-sizing: border-box;
  -moz-box-sizing: border-box;
  box-sizing: border-box;
  -webkit-border-radius: 1px;
  -moz-border-radius: 1px;
  border-radius: 1px;
}
.emailreqsub{
	margin:10px auto;
	height:25px;
	text-align:centre;	
	float:right;

}

.emailreqlbl{
   font-size: 14px;
   font-weight:bold;
  height: 32px;
  color: #444;
  margin: 0px 0;
  display: block;
  line-height: 32px;
}
#emailreqbx hr{
margin: 25px 0;
}
</style>
<div id="emailreqbx">
<h2><label class="emailreqlbl" >Email is required for Authentication.</label></h2>
<?php echo $this->RegistrationForm; ?>
<!-- 	<form id="emailreqfrm" action="/emailrequired" method="post"> -->
<!-- 		<input class="emailreqinp" type="email" name="email" value="" placeholder="email"/> -->
<!-- 		<input class="emailreqsub btn" type="submit" value="update email" /> -->
<!-- 	</form> -->
</div>