<ul id="apilgbx">
    <li><a href="<?php echo BASE_PATH ?>apilogin/google" class="apiw apih apif apicn gicn"
           onclick="window.open(this.href, 'auth', 'width=700,height=600');
                   return false;">login
            with gmail</a></li>

    <li><a href="<?php echo BASE_PATH ?>apilogin/facebook" class="apiw apih apif apicn fbicn"
           onclick="window.open(this.href, 'auth', 'width=700,height=600');
                   return false;">login
            with facebook</a></li>

    <!-- 	<li><a href="/apilogin/twitter" class="apicn ticn"
                    onclick="window.open(this.href, 'auth', 'width=700,height=600'); return false;">login
                            with twitter</a></li> 
            <li><a href="/apilogin/yahoo" class="apicn yicn"
                    onclick="window.open(this.href, 'auth', 'width=700,height=600'); return false;">login
                            with yahoo</a></li>-->
</ul>