<?php
// function fetch_highest_res($videoid) {
// $image_qualities = array('mqdefault');
// //in the order of preference
//
// foreach ($image_qualities as $image_quality) {
// if (@getimagesize(('http://i.ytimg.com/vi/' . $videoid . '/' . $image_quality . '.jpg'))) {
// $imgurl = "http://i.ytimg.com/vi/$videoid/$image_quality.jpg";
// return $imgurl;
// break; //exiting
// }
// }
// }
//
// function truncate($str, $len) {
// $tail = max(0, $len - 10);
// $trunk = substr($str, 0, $tail);
//
// $trunk .= strrev(preg_replace('~^..+?[\s,:]\b|^...~', '...', strrev(substr($str, $tail, $len - $tail))));
// if (strlen($str) > $len + 1) {
// return $trunk . "<br/><span class='readmore'>......<span class='readmore'>read more</span></span>";
// } else {
// return $trunk;
// }
// }
$firstName = 'fname';
$username = 'fname';
$message = 'message';
$url = 'url';
$profileImage = 'profile_image_link';
$videoTitle = 'video_title';

$dedicatedUserDetail = $this->dedicatedUserDetails;
$dedicatedUserDetail ['dedicationtounknowuser'] = $dedicatedUserDetail ['dedicated_unknown_user'];
// echo "<pre>" . print_r($dedicatedUserDetail, 1);
// exit('sdsd');

// if (empty($dedicatedUserDetail[$profileImage])) {
// $dedicatedUserDetail[$profileImage];
// }

?>
<div class='ded'>
	<div class='dedf'>
		<div class="dedfu">
			<div class='dedic-block'>
                <?php // if (!empty($dedicatedUserDetail[$url])) {  ?>

                <div class="dedic-block-data">
					<!--<div class="dedic-block-data-l">        
                        <div class="reframe">
                            <img src="/img/album/1.jpeg" class="inactiveImg" style="float: left;" />
                            <img src="/img/album/2.jpg" class="inactiveImg" style="float: left;" />
                            <img src="/img/album/3.jpg" class="inactiveImg" style="float: left;" />
                            <img src="/img/album/5.jpg" class="inactiveImg" style="float: left;" />

                        </div>

                        <div class="reframelayer"></div>
                        <div>
                            <img src=""/>
                        </div>
                    </div>-->
                    <?php
						if (! empty ( $dedicatedUserDetail [$url] )) {
							?>
                        <div class="dedic-block-data-r">
						<div class="data" id="XNMMrbHMiNM">
							<div>
                                    <?php
									// $json = json_decode(file_get_contents("http://gdata.youtube.com/feeds/api/videos/XNMMrbHMiNM?v=2&alt=jsonc"));
									echo '<img class="dedic-block-data-img" src="' . $this->Resolution ( $dedicatedUserDetail [$url] ) . '">';
									?>
           <!--                        <img class="dedic-block-data-img" src="http://i1.ytimg.com/vi/cZGQkzeg6kE/default.jpg" />-->
								<!--<a class="dedic-block-hvrimg" href='' style='background-image:url("<?php echo isset($dedicatedUserDetail[$profileImage]) ? $dedicatedUserDetail[$profileImage] : '/images/user.gif'; ?>")'></a>-->
								<div class="dedic-block-uhvr">

									<div class='dedic-block-uhvrb'>
										<div class="dedic-block-uhvrb-lbl">
                                                <?php echo $dedicatedUserDetail[$videoTitle]; ?>
                                            </div>
										<i class='dedic-block-uhvrbplbn'></i>
									</div>
								</div>
							</div>
							<div class="video" id=""></div>
						</div>

					</div><?php } ?>
                    <div class="dedic-block-data-l">
						<div class='dedh'>
							<div class='dedh_lcontainer'>
								<div class='profimg'>
									<a href = "<?php echo $dedicatedUserDetail[$firstName] ?>" style = "background-image:url('<?php echo empty($dedicatedUserDetail[$profileImage]) ? 'images/user.gif' : $dedicatedUserDetail[$profileImage]; ?>');"></a>
								</div>
							</div>
							<div class='dedh_rcontainer'>
								<div class='deta-block'>
									<div class='dedh_hblockl'>
										<div class="dedh_hblocklt">
											<span style="margin-left: 5px;" class='profname'><a
												href='<?php echo $dedicatedUserDetail[$username]; ?>'><?php echo $dedicatedUserDetail[$firstName]; ?></a></span>
											<span style="margin-left: 10px;" class='dedprofname'></span>
											<span class='dediccreated'><?php echo $dedicatedUserDetail['created']; ?></span>

											<input type='hidden' class='currentuserauth'
												value='<?php echo $dedicatedUserDetail['id']; ?>' />
										</div>
										<div class="dedh_hblocklb">
											<div class="dedh_hblocklblbl">dedicate to:</div>
											<ul>                                  
                                                <?php
												$el = '';
												if(!empty($dedicatedUserDetail ['dedicationtouser'])){
													foreach ( $dedicatedUserDetail ['dedicationtouser'] as $dedicatioToUserDetail ) {
														// $dedicatedUserDetail[$profileImage] = $dedicatioToUserDetail[$profileImage];
														
														// if (empty($dedicatedUserDetail[$profileImage])) {
														// $dedicatedUserDetail[$profileImage] = '';
														// }
														
														$el .= "<li><a href='" . $dedicatioToUserDetail ['fname'] . "'><img class='deduserimage'  style='box-shadow: 0 -2px 4px 0 rgba(0, 0, 0, 0.15); position:absolute;margin-left:5px; border-radius: 3px' height='22' width='22' src='" . isset ( $dedicatioToUserDetail [$profileImage] ) ? $dedicatioToUserDetail [$profileImage] : '/images/user.gif' . "'/></a></li>";
													}
												}
												$dedicatedUserDetails = unserialize ( $dedicatedUserDetail ['dedicationtounknowuser'] );
												if (! empty ( $dedicatedUserDetails )) {
													foreach ( $dedicatedUserDetails as $dedicationtounknowuser ) {
														// echo $dedicationtounknowuser."<br>";
														// $dedicatedUserDetail[$profileImage] = $dedicatioToUserDetail[$profileImage];
														//
														// if (empty($dedicatedUserDetail[$profileImage])) {
														// $dedicatedUserDetail[$profileImage] = '';
														// }
														
														$el .= "<li><a href='" . $dedicationtounknowuser . "'>{$dedicationtounknowuser}&nbsp&nbsp</a></li>";
														// . "<!--img class='deduserimage' style='box-shadow: 0 -2px 4px 0 rgba(0, 0, 0, 0.15); position:absolute;margin-left:5px; border-radius: 3px' height='22' width='22' src='" . isset($dedicationtounknowuser[$profileImage]) ? $dedicationtounknowuser[$profileImage] : '/images/user.gif' . "'/-->".$dedicationtounknowuser.;
													}
													
												}
												echo $el;
												?>
                                            </ul>
										</div>
									</div>
								</div>
								<div class="dedh_hblockr">
									<!--img src="<?php echo $dedicatedUserDetail[$profileImage]; ?>"/-->
								</div>
								<!--<div class="dedh_hblockb">
                                        <div class="dedicated_user_block"> 
                                          <span class='dediccreated'><?php echo $dedicatedUserDetail['created']; ?></span>
                                        </div>
                                </div>-->
							</div>
						</div>


						<div class='dedicated_user_block_txt'>"<?php
						// echo "<pre>".print_r($dedicatedUserDetail[$message],1);exit("sd");
						if (isset ( $dedicatedUserDetail [$message] ) && ! empty ( $dedicatedUserDetail [$message] )) {
							echo $this->TruncateMessage ( ucfirst ( $dedicatedUserDetail [$message] ), 180 );
						}
						?>"
                        </div>
					</div>
				</div>
				<div class="clearfx"></div>
				<div class="dedic-block-data-info"></div>

                <?php
				// }
				// echo "<pre>".print_r($dedicatedUserDetail,1);exit;
				?>               
            </div>
		</div>
	</div>
	<div class="mscontainer">
		<div class='disq-block'>
			<ul>

			</ul>
		</div>
		<div class='usrcmntbxb'>
			<div class='lusrcmntbx'>
				<form>
					<div id="" class='replybx writebx write txth txtb divtxtar'
						contenteditable='true'></div>
					<input class='inwrite' type='hidden' value='' /> <input
						class='inwriteid' type='hidden'
						value='<?php echo $dedicatedUserDetail['dedication_id']; ?>' /> <input
						class='touserid' type='hidden'
						value='<?php echo $dedicatedUserDetail['id']; ?>' />
				</form>
			</div>
			<div class='rusrcmntbx'>
				<div class='trusrcmntbx'>
					<img
						src='<?php echo !empty($dedicatedUserDetail[$profileImage])?$dedicatedUserDetail[$profileImage] : '/images/user.gif';  ?>'
						style='border-radius: 4px 4px 4px 4px; height: 30px; width: 30px;' />

				</div>
				<!--div class='brusrcmntbx'>
                    <ul>
                        <li class='btn postbtn'><span>Post</span></li>                      
                        <li class='btn cnclbtn'><span>Cancel</span></li>                       
                    </ul>
                </div-->
			</div>
		</div>
		<div class='usrcmntbxa writebx write txta'>write..</div>
		<!--div class='usrcmntbxa'>
             <div class='usrcmntbxadiv writebx write txth txta'>write..</div>
         </div-->
	</div>
</div>
<div class="upldblck"></div>
<?php exit(); ?>