<?php
/**
 * working file
 */
//echo "******88S88";
//exit();
$dedicatedUserDetail = $this->dedicatedUserDetails;
//  echo "<pre>" . print_r($dedicatedUserDetail, 1);
//exit('sdsd');
//if (empty($dedicatedUserDetails)) {
//    echo $this->partial('partials/newuser.phtml', array('newuserprofile' => $this->newUserProfile));
//}`
//echo "<pre>" . print_r($dedicatedUserDetails, 1);exit('sss');
//foreach ($dedicatedUserDetails as $dedicatedUserDetail) {

$firstName      = 'fname';
$username       = 'fname';
$message        = 'message';
$url            = 'url';
$profileImage   = 'profile_image_link';
$videoTitle     = 'video_title';
// echo "<pre>".print_r($dedicatedUserDetails,1);exit;
// if (empty($dedicatedUserDetails[0][$profileImage]) || !isset($dedicatedUserDetails[$profileImage])) {
//     $dedicatedUserDetails[0][$profileImage];
// }

// if(count($dedicatedUserDetails)>0):
// foreach ($dedicatedUserDetails as $dedicatedUserDetail ){
    $dedicated_image_links = unserialize($dedicatedUserDetail['dedicated_image_link']);
    if((isset($dedicatedUserDetail[$url]) && !empty($dedicatedUserDetail[$url])) &&
            (isset($dedicated_image_links) && !empty($dedicated_image_links))
            ){
        $width = "100%";
    }
?>
<div class='ded dedid<?php echo $dedicatedUserDetail['id'] ?>'>
    <div class='dedsetting'>x</div>
	<input type='hidden' class='dedid'
		value='<?php echo $dedicatedUserDetail['id'] ?>' />
    <div class='dedf'>
        <div class="dedfu">
            <div class='dedh_hblockl'>
                                        <div class="dedh_hblocklt">
                                            <span style=" margin-left: 5px;" class='profname'><a href='<?php echo $dedicatedUserDetail[$username]; ?>'><?php echo $dedicatedUserDetail[$firstName]; ?></a></span>
                                            <span style=";margin-left: 0px;" class='dedprofname'></span>
                                            
                                            <span class='dediccreated'><?php echo $this->TimeAgo($dedicatedUserDetail['created']); ?></span>
                                            <input type='hidden' class='currentuserauth' value='<?php
                                            
                                            echo $dedicatedUserDetail['id']; ?>'/>
                                        </div>   
                                    </div>
            <div class='dedic-block'>
                <?php // if (!empty($dedicatedUserDetail[$url])) {  ?>
                
                <div class="dedic-block-data">
                    <!--<div class="dedic-block-data-l">        
                        <div class="reframe">
                            <img src="/img/album/1.jpeg" class="inactiveImg" style="float: left;" />
                            <img src="/img/album/2.jpg" class="inactiveImg" style="float: left;" />
                            <img src="/img/album/3.jpg" class="inactiveImg" style="float: left;" />
                            <img src="/img/album/5.jpg" class="inactiveImg" style="float: left;" />

                        </div>

                        <div class="reframelayer"></div>
                        <div>
                            <img src=""/>
                        </div>
                    </div>-->
                    <div class="dedic-block-data-l">
                        <div class='dedh'>
                            <div class='dedh_lcontainer'>
                                <div class='profimg'>
                                    <a href = "<?php                                    
                                    echo $dedicatedUserDetail[$firstName] ?>" style = "background-image:url('<?php echo empty($dedicatedUserDetail[$profileImage]) ? 'images/user.gif' : $dedicatedUserDetail[$profileImage]; ?>');"></a>
                                </div>                   
                            </div>
                            <div class='dedh_rcontainer'>
                                <div class='deta-block'>
                                    
                                        <div class="dedh_hblocklb">
                                            <ul>                                  
                                                <?php 
                                                $el = '';
                                                if(isset($dedicatedUserDetail['dedicationtouser']) && !empty($dedicatedUserDetail['dedicationtouser'])){
                                                    foreach ($dedicatedUserDetail['dedicationtouser'] as $dedicatioToUserDetail) {
                                                        $dedicatedUserDetail[$profileImage] = $dedicatioToUserDetail[$profileImage];
//                                                           $el .= "<li><a href='" . $dedicatioToUserDetail['fname'] . "'><img class='deduserimage'  style='box-shadow: 0 -2px 4px 0 rgba(0, 0, 0, 0.15); position:absolute;margin-left:5px; border-radius: 3px' height='22' width='22' src='" . $dedicatioToUserDetail[$profileImage] . "'/></a></li>";
                                                            $el .= "<li><a href='" . $dedicatioToUserDetail['fname'] . "'>" . $dedicatioToUserDetail['fname'] . "</a></li>";
                                                    }
                                                }
                                                if(isset($dedicatedUserDetail['dedicationtounknowuser']) && !empty($dedicatedUserDetail['dedicationtounknowuser'])){
                                                    $dedicationtounknowusers = $dedicatedUserDetail['dedicationtounknowuser'];
                                                    foreach ($dedicationtounknowusers as $dedicationtounknowuser) {
                                                        //$dedicatedUserDetail[$profileImage] = $dedicationToUserDetail[$profileImage];
                                                            $el .= "<li><a href='" . $dedicationtounknowuser . "'>".$dedicationtounknowuser."</a></li>";
                                                    }
                                                }
                                                echo $el;
                                                ?>
                                            </ul>
                                             <div  class='dedicated_user_block_txt'><?php echo !empty($dedicatedUserDetail[$message]) ? "\"".$this->TruncateMessage(ucfirst($dedicatedUserDetail[$message])."\"", 180) : ''; ?>
                        </div>
                                        </div>
                                </div>
                                <div class="dedh_hblockr">
                                    
                                </div>
                                <!--<div class="dedh_hblockb">
                                        <div class="dedicated_user_block"> 
                                          <span class='dediccreated'><?php //echo gettimeago($dedicatedUserDetail['created_date']); ?></span>
                                        </div>
                                </div>-->
                            </div>  
                        </div>


                       
                        <div class="clearfx"></div>
                        <div>
                            
                        </div>
                    </div>
                        <div class="dedic-block-data-r">
                        <?php if (!empty($dedicatedUserDetail[$url])) { ?>
                            <div style="width:272px; position:relative;z-index: 0;float: right" class="data" id="XNMMrbHMiNM">
                                <div>
                                    <?php
                                    // $json = json_decode(file_get_contents("http://gdata.youtube.com/feeds/api/videos/XNMMrbHMiNM?v=2&alt=jsonc"));
                                    echo '<img class="dedic-block-data-img" src="' . $this->Resolution($dedicatedUserDetail[$url]) . '">';
                                    ?>
           <!--                        <img class="dedic-block-data-img" src="http://i1.ytimg.com/vi/cZGQkzeg6kE/default.jpg" />-->
                               <!--<a class="dedic-block-hvrimg" href='' style='background-image:url("<?php echo $dedicatedUserDetail[$profileImage]; ?>")'></a>-->
                                    <div class="dedic-block-uhvr">

                                        <div class='dedic-block-uhvrb'>
                                            <div class="dedic-block-uhvrb-lbl">
                                                <?php echo $dedicatedUserDetail[$videoTitle]; ?>
                                            </div>
                                            <i class='dedic-block-uhvrbplbn'></i>
                                        </div>
                                    </div>  
                                </div>
                                <div class="video" id=""></div>
                            </div>
                            <?php } ?>
                                <?php
                                   //$dedicated_image_links = unserialize($dedicatedUserDetail['dedicated_image_link']);
// echo "<pre>".print_r($dedicated_image_links,1);echo "hello";
                                   if(isset($dedicated_image_links) && !empty($dedicated_image_links)){
                                    ?>
                                    <div class="dedic-block-image-data">
                                        <ul>
                                        <?php   
                                            echo $this->createCollage($dedicated_image_links);
                                        ?>
                                        </ul>
                                    </div>
                                    <?php
                                    }
                                ?>
                        </div>
                    <div class="clearfx"></div>
                </div>
                
                <div class="dedic-block-data-info">                    
                </div>

                <?php
//            }
//                echo "<pre>".print_r($dedicatedUserDetail,1);
                ?>               
            </div>
        </div>            
    </div>  
    <div class="mscontainer"> 
        <div class='disq-block'>
            <ul>
                <?php
//                $dedicatedUserDetail['dedicationbyusercomment'] = 4;
                if(!empty($dedicatedUserDetail['dedicationbyusercomment'])){
                $comments = array_slice($dedicatedUserDetail['dedicationbyusercomment'], -2, 2, true);
                
                foreach ($comments as $comment) {
                    $commentprofileimage = $comment[$profileImage];
                    $commentcomment = $comment['comment'];
                    $commentcreated = $comment['created'];
                    $commentid = $comment['id'] = '2';
                    ?>  

                    <li class='disqli'>
                        <div class='ldisq'><img  src='<?php echo !empty($dedicatedUserDetail['dedicationtouser'][$profileImage])?$dedicatedUserDetail['dedicationtouser'][$profileImage] : '/images/user.gif'; ?>' style='width:26px;height:26px;border-radius: 2px 2px 2px 2px;'/></div>
                        <div class='rdisq'><span class='cmnt'><?php echo $commentcomment; ?></span>
                            <span class='cmntdttm'><?php echo date('D d-m-Y H:i:a', strtotime($commentcreated)); ?></span>
                            <span class='deletecms'>x</span>
                        </div>
                        <input class='commentid' type='hidden' value='<?php echo $commentid; ?>'/>
                    </li>
<?php }} ?>
            </ul>
        </div>            
        <div class='usrcmntbxb'>
            <div class='lusrcmntbx'>
                <form>
                    <div id="" class='replybx writebx write txth txtb divtxtar' contenteditable='true'></div>
                    <input class='inwrite' type='hidden' value=''/>
                    <input class='inwriteid' type='hidden' value='<?php echo $dedicatedUserDetail['id']; ?>'/>
                    <input class='touserid' type='hidden' value='<?php echo $dedicatedUserDetail['id']; ?>'/>
                </form>
            </div>
            <div class='rusrcmntbx'>
                <div class='trusrcmntbx'>
                    <img src='<?php echo !empty($dedicatedUserDetail[$profileImage])?$dedicatedUserDetail[$profileImage] : '/images/user.gif';  ?>' style='border-radius:4px 4px 4px 4px;height:30px;width:30px;'/>

                </div>
                <!--div class='brusrcmntbx'>
                    <ul>
                        <li class='btn postbtn'><span>Post</span></li>                      
                        <li class='btn cnclbtn'><span>Cancel</span></li>                       
                    </ul>
                </div-->
            </div>
        </div>
        <div class='usrcmntbxa writebx write txta'>write..</div>
        <!--div class='usrcmntbxa'>
             <div class='usrcmntbxadiv writebx write txth txta'>write..</div>
         </div-->
    </div>
</div>

<div class="upldblck"></div>
