<div id='ststsppdv' class='ststsppdv'>
	<span class='clststsppdv'>close</span>
	<form id='crntlyim' enctype='multipart/form-data'>
		<div class='crntlyimt'>
			<div class='crntlyimtdvt'>
				<div class='tooltip'>eg: watching movie.</div>
				<div class='crntlyimtdvta'>
					<div class='crntlyimtdvtadv'>
						<div id='bef'>
							<span class='befspn'></span> <span class='befspnlbl'></span>
						</div>
						<input autocomplete='off' id='crntlyimtdvtdv'
							placeholder='what you are doing?' class='crntlyimtdvtdv' /> <input
							id='crntlyimtdvtinp' class='crntlyimtdvtinp' type='hidden'
							placeholder='What you are doing now: ' value='' />
					</div>
			<!--input autocomplete='off' class='ststsppdvimgupbtn btn btn-sbmt' type='button' value='+ upload images'/-->
			<input autocomplete='off' name='ststsppdvimgupbtnrg'
				id='ststsppdvimgupbtnrg' type='file' class='ststsppdvimgupbtnrg' />
			<input id='crntlyimsubmit' type='button' class='btn btn-sbmt'
				value='add'>
					<div class='crntlyimtdvtab'>
						<span id='crntlyimtdvtabwth'></span> <span
							class='crntlyimtdvtabspna'></span> <span
							class='crntlyimtdvtabspnafl'></span>
					</div>
					<div class='ststsppdvimg'>
						<div id='ststsppdvimgbdy' class='ststsppdvimgbdy'>
							<ul></ul>
						</div>
						<div class='ststsppdvimgaddv ststsppdvimgupbtn'>
							<span>+ current photos</span>
						</div>
						<div class='ststsppdvimgbdya' id='ststsppdvimgbdya'>
							<ul></ul>
						</div>
					</div>
					<div class='crntlyimtdvb'>
						<div class='tooltip'>Press enter to add people</div>
						<div class='crntlyimtdvba'>
							<span class='crntlyimtdvbawth'>+</span><input autocomplete='off'
								type='text' placeholder='with whom you are ?'
								id='crntlyimtdvbinpa' class='crntlyimtdvbinpa'>
							<!--span class='crntlyimtdvbafl'>?</span><div class='crntlyimtdvbaflndv'><input autocomplete='off' placeholder='How you feel now?' type='text' id='crntlyimtdvbinpb' class='crntlyimtdvbinpb'></div-->
						</div>
					</div>
				</div>
			</div>
        </form>
</div>