<div class="fppl" >
    <div class="fppl">
        <input type="text" placeholder="Find People" class="fpplin" id="fpplin" />
    </div>
    <div class="fppb">
        <div classs="fppbi">
           <li class='frndlstid'>
               <div class='frndlstcntnriimg'>
                   <img src='" +  + "' style='width:35px;'/>
               </div>
               <div class='frndlstcntnridv'>
                   <div class='frndlstcntnridva'>
                       <a href=''></a>
                   </div>
                   <div class='frndlstcntnridvb'>
                       <div class='checkbox'></div>                           
                   </div>                       
               </div>
           </li>
        </div>
    </div>
</div>