<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
    <head>
        <?php echo $this->headMeta() ?>
        <meta name="language" content="en" />
        <title>Oops! There's Been A Problem!</title>
    </head>
    <body>
        <h1>An Error Has Occurred</h1>
        <?php if ($this->statusCode == 500): ?>
            <p>ERROR.phtml <500>: We're truly sorry, but we cannot complete your request at this
                time.</p>
            <p>If it's any consolation, we have scheduled a new appointment
                for our development team leader in Torture Chamber #7 to encourage
                his colleagues to investigate this incident.</p>
        <?php else: ?>
            <p>ERROR.phtml < <?php echo $this->statusCode ?> >: We're truly sorry, but the page you are trying to locate
                does not exist.</p>
            <p>Please double check the requested URL or consult your local.</p>
        <?php endif; ?>
    </body>
</html>
