<div class='usrcntc mycontact'>
    <ul>
        <li>
            <div class='usrcntlbl'>email</div>
            <div class="usrcntdsc">
                <span>gurjeetsbagga@gmal.com</span>
            </div>
        </li>
        <li>
            <div class='usrcntlbl'>Phone number</div>
            <div class="usrcntdsc">
                <span>7829885480</span>
            </div>
        </li>
        <li>
            <div class='usrcntlbl'>Mobile number</div>
            <div class="usrcntdsc">
                <span>7829885480</span>
            </div>
        </li>
    </ul>
</div>