<div class='usredbx myeducation'>
    <ul>
        <li>				
            <div class="uedim" style='background-image:url("cl.jpg")'></div>				
            <div class="usered">
                <div class='uedyr'>
                    <a href="">NIT Jaipur</a>-<span>2006-2010</span>
                </div>				
                <div class='uedyrdsc'>
                    <label>B-Tech: Computer Science</label>					
                </div>
            </div>				
        </li>
                                                            
        <li>				
            <div class="uedim" style='background-image:url("cl.jpg")'></div>				
            <div class="usered">
                <div class='uedyr'>
                    <a href="">Kendriya Vidyala No.2</a>-<span>1996-2003</span>
                </div>				
                <div class='uedyrdsc'>
                    <label>Standard: 9 to 12</label>					
                </div>
            </div>				
        </li>
        <li>				
            <div class="uedim" style='background-image:url("cl.jpg")'></div>				
            <div class="usered">
                <div class='uedyr'>
                    <a href="">Kendriya Vidyala Skh line</a>-<span>1990-1996</span>
                </div>				
                <div class='uedyrdsc'>
                    <label>Standard: 3 to 8</label>					
                </div>
            </div>				
        </li>
                                                            
        <li>				
            <div class="uedim" style='background-image:url("cl.jpg")'></div>				
            <div class="usered">
                <div class='uedyr'>
                    <a href="">Army School</a>-<span>1988-1990</span>
                </div>				
                <div class='uedyrdsc'>
                    <label>LKG</label>					
                </div>
            </div>				
        </li>
    </ul>
</div>