<?php
var_dump($this->user);exit;
?>
<div class="usrfd myfriends" >
    <ul>
        <li>
            <a href=""><img src="hr.jpg"></a>
            <span>Rahul Kumar</span>
            <!-- date show to me only -->
            <div class='usrfded'>(since 1 year)</div>
            <div class="userfdop">
                <ul>
                    <li>friends</li>
                    <li>remove</li>
                </ul>
            </div>
        </li>
        <li>
            <button class='mimgafbtn'>+ Add Friend</button>
        </li>
    </ul>
</div>