<div class='usrlv myliving'>
    <ul>
        <li>				
            <div class="uedim" style='background-image:url("cl.jpg")'></div>				
            <div class="usered">
                <div class='uedyr'>
                    <a href="">Bangalore</a>-<span>2002-present</span>
                </div>				
                <div class='uedyrdsc'>
                    <label>Karnatak</label>				
                </div>
            </div>				
        </li>
    </ul>
</div>