<div class='usrprf myprofessional'>
    <ul>
        <li>				
            <div class="uedim" style='background-image:url("cl.jpg")'></div>				
            <div class="usered">
                <div class='uedyr'>
                    <a href="">Cognizant Technology Solution</a>-<span>2002-present</span>
                </div>				
                <div class='uedyrdsc'>
                    <label>Software Developer</label>
                    <label>Bangalore</label>					
                </div>
            </div>				
        </li>
                                                            
        <li>				
            <div class="uedim" style='background-image:url("cl.jpg")'></div>				
            <div class="usered">
                <div class='uedyr'>
                    <a href="">edureka.in</a>-<span>1996-2003</span>
                </div>				
                <div class='uedyrdsc'>
                    <label>Php Developer</label>	
                    <label>Bangalore</label>				
                </div>
            </div>				
        </li>
        <li>				
            <div class="uedim" style='background-image:url("cl.jpg")'></div>				
            <div class="usered">
                <div class='uedyr'>
                    <a href="">Nimbus Software Pvt. Ltd</a>-<span>1990-1996</span>
                </div>				
                <div class='uedyrdsc'>
                    <label>Software Developer</label>		
                    <label>Bangalore</label>			
                </div>
            </div>				
        </li>
    </ul>
</div>