<div class='ursb mysibling' >
    <div class="usrsb">
        <ul>
            <li class="sbgrplst">
                <div>Brother</div>
                <ul class="sblst">
                    <li>
                        <a href=""><img src="hr.jpg"></a>
                        <span>Rahul Kumar</span>
                        <!-- date show to me only -->
                        <div class='usrfded'>(since 1 year)</div>
                        <div class="userfdop">
                            <ul>
                                <li>brother</li>
                                <li>remove</li>
                            </ul>
                        </div>
                    </li>
                </ul>
            </li>					
        </ul>
    </div>
</div>